<x-app-layout>
    <x-slot name="header"><h1 class="font-serif text-3xl text-dokun-green">{{ $mode === 'admin' ? 'Pilotage ƉƆKUN' : 'Mon espace' }}</h1></x-slot>
    @if($mode === 'visitor')
    <div class="min-h-screen bg-dokun-ivory py-8"><div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <section class="rounded-3xl bg-dokun-green text-white p-8 md:p-10"><p class="text-dokun-gold text-xs font-bold tracking-[.18em] uppercase">Votre carnet de voyage</p><h2 class="font-serif text-4xl mt-2">Bonjour, {{ Auth::user()->name }}</h2><p class="mt-3 text-white/75">Retrouvez vos réservations et continuez l’exploration de Porto-Novo.</p><a href="{{ route('experiences.index') }}" class="inline-block bg-dokun-gold rounded-xl px-5 py-3 mt-6 font-bold">Découvrir une expérience</a></section>
        <section class="bg-white rounded-2xl border border-black/5 mt-8 overflow-hidden"><div class="p-6 border-b"><h2 class="font-serif text-2xl text-dokun-green">Mes réservations</h2></div><div class="divide-y">@forelse($reservations as $reservation)<article class="p-6 flex flex-wrap justify-between gap-4"><div><h3 class="font-bold">{{ $reservation->experience_type }}</h3><p class="text-sm text-dokun-charcoal/60 mt-1">{{ \Carbon\Carbon::parse($reservation->requested_date)->translatedFormat('l d F Y') }} · {{ $reservation->guests_count }} personne(s)</p><p class="text-xs mt-2 text-dokun-charcoal/50">Référence {{ $reservation->reference }}</p></div><span class="self-start rounded-full px-3 py-1 text-xs font-bold {{ $reservation->status === 'accepted' ? 'bg-emerald-100 text-emerald-800' : ($reservation->status === 'rejected' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-800') }}">{{ ['pending'=>'En attente','accepted'=>'Confirmée','rejected'=>'Refusée','completed'=>'Réalisée'][$reservation->status] }}</span></article>@empty<div class="p-12 text-center text-dokun-charcoal/60">Aucune réservation enregistrée. <a class="font-bold text-dokun-green underline" href="{{ route('experiences.index') }}">Explorer les expériences</a></div>@endforelse</div></section>
    </div></div>
    @else
    <div class="min-h-screen bg-dokun-ivory py-8"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <section class="rounded-3xl bg-dokun-green text-white p-8 md:p-10 relative overflow-hidden"><img src="{{ asset('images/hero/tourisme_porto_novo.png') }}" alt="" class="absolute inset-0 w-full h-full object-cover opacity-15"><div class="relative"><p class="text-dokun-gold text-xs font-bold tracking-[.18em] uppercase">Espace administration</p><h2 class="font-serif text-4xl mt-2">Bonjour, {{ Auth::user()->name }}</h2><p class="mt-3 text-white/75 max-w-2xl">Gardez une vue simple sur les savoir-faire, les détenteurs et les demandes de visite.</p></div></section>
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-5 my-7">@foreach([['Artisans',$stats['artisans_count']],['Savoir-faire',$stats['categories_count']],['Réservations',$stats['reservations_count']],['À traiter',$stats['pending_reservations']]] as [$label,$value])<div class="bg-white rounded-2xl p-6 border border-black/5"><p class="text-sm font-semibold text-dokun-charcoal/55">{{ $label }}</p><p class="font-serif text-4xl text-dokun-green mt-2">{{ $value }}</p></div>@endforeach</div>
        <section class="bg-white rounded-2xl p-7 border border-black/5"><h2 class="font-serif text-2xl text-dokun-green">Actions rapides</h2><div class="flex flex-wrap gap-3 mt-5"><a href="{{ route('admin.artisans.create') }}" class="bg-dokun-green text-white px-5 py-3 rounded-xl font-bold">Ajouter un artisan</a><a href="{{ route('admin.savoir-faires.index') }}" class="border border-dokun-green text-dokun-green px-5 py-3 rounded-xl font-bold">Gérer les contenus</a><a href="{{ route('admin.reservations.index') }}" class="bg-dokun-gold text-white px-5 py-3 rounded-xl font-bold">Voir les réservations</a></div></section>
    </div></div>
    @endif
</x-app-layout>
