<x-app-layout>
    <x-slot name="header"><h1 class="font-serif text-3xl text-dokun-green">Mon atelier</h1></x-slot>
    <div class="min-h-screen bg-dokun-ivory py-8"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="mb-6 bg-emerald-50 text-emerald-800 rounded-xl p-4 font-semibold">{{ session('success') }}</div>@endif
        @if(!empty($notice))<div class="bg-white rounded-2xl p-10 text-center"><h2 class="font-serif text-3xl text-dokun-green">Bienvenue sur votre espace professionnel</h2><p class="mt-3 text-dokun-charcoal/65">{{ $notice }}</p><a href="{{ route('profile.edit') }}" class="inline-block mt-6 bg-dokun-green text-white px-6 py-3 rounded-xl font-bold">Compléter mon compte</a></div>
        @else
        <section class="rounded-3xl bg-dokun-green text-white p-7 md:p-10 relative overflow-hidden"><img src="{{ $artisan->image_url }}" alt="" class="absolute inset-0 h-full w-full object-cover opacity-20"><div class="relative"><p class="text-dokun-gold uppercase font-bold tracking-wider text-xs">Espace détenteur</p><h2 class="font-serif text-4xl mt-2">{{ $artisan->professional_name ?: $artisan->first_name.' '.$artisan->last_name }}</h2><p class="mt-3 text-white/75">Suivez vos demandes et préparez vos prochaines rencontres.</p><a href="{{ route('artisans.show', $artisan) }}" class="inline-block mt-6 bg-white text-dokun-green px-5 py-3 rounded-xl font-bold">Voir ma fiche publique</a></div></section>
        <div class="grid sm:grid-cols-3 gap-5 my-7">@foreach(['pending'=>'À répondre','accepted'=>'À préparer','completed'=>'Réalisées'] as $key=>$label)<div class="bg-white rounded-2xl p-6 border border-black/5"><p class="text-dokun-charcoal/55 text-sm font-semibold">{{ $label }}</p><p class="font-serif text-4xl text-dokun-green mt-2">{{ $stats[$key] }}</p></div>@endforeach</div>
        <section class="bg-white rounded-2xl border border-black/5 overflow-hidden"><div class="p-6 border-b"><h2 class="font-serif text-2xl text-dokun-green">Demandes de réservation</h2></div><div class="divide-y">@forelse($reservations as $reservation)<article class="p-6 flex flex-col md:flex-row md:items-center gap-5 justify-between"><div><h3 class="font-bold">{{ $reservation->experience?->title ?: $reservation->experience_type }}</h3><p class="text-sm text-dokun-charcoal/60 mt-1">{{ $reservation->visitor_name }} · {{ \Carbon\Carbon::parse($reservation->requested_date)->translatedFormat('l d F') }} · {{ $reservation->guests_count }} personne(s)</p><p class="text-sm text-dokun-charcoal/60">{{ $reservation->visitor_phone }} @if($reservation->visitor_email) · {{ $reservation->visitor_email }} @endif</p></div><form method="POST" action="{{ route('artisan-space.reservations.update', $reservation) }}" class="flex gap-2">@csrf @method('PATCH')<select name="status" class="rounded-xl border-gray-200 text-sm"><option value="accepted">Accepter</option><option value="rejected">Refuser</option><option value="completed">Marquer réalisée</option></select><button class="bg-dokun-green text-white rounded-xl px-4 py-2 font-bold text-sm">Enregistrer</button></form></article>@empty<div class="p-10 text-center text-dokun-charcoal/55">Aucune demande pour le moment.</div>@endforelse</div>@if($reservations->hasPages())<div class="p-5">{{ $reservations->links() }}</div>@endif</section>
        @endif
    </div></div>
</x-app-layout>
